# Medidas de centralidade e viabilidade

Considere os valores assumidos por uma variável quantitativa, a partir desses valores vamos estabelecer medidas correspondentes a um resumo da distribuição de tais valores.

Um valore médio ou central é um valor indicativo do grau de variabilidade ou dispersão em torno do valor central.

Como valores centrais estudaremos a média, a mediana e a moda.

Como medida de variabilidade estudaremos a variância, o desvio padrão e o desvio médio.

## Média aritmética

Seja $x = (x_1, x_2, \ldots, x_n)$ uma variável quatitativa.
A média aritmética de $x (\overline{x})$ é a divisão da soma de todos os valores de $x$ pelo número de valores de $x$
$$
\overline{x} = \frac{\sum_{i=1}^{n} x_i}{n}  
$$

### Exemplo

Um aluno fez 12 simulados em uma escola ao longo do ano.
Em casa simulado, o número de questões era 80.
A seguir número de questões acertadas pelo aluno.
$$
x = (56, 52, 61, 63, 48, 68, 49, 59, 61, 62, 60, 55)
$$
A média aritmética desses do aluno no simulado
 $
 \begin{align}
\overline{x} & = \frac{\sum_{i=1}^{n} x_i}{12} \\
& = \frac{684}{12} \\
& \approx 57.83  
\end{align}
$

A nota média obtida por esse aluno foi 57 pontos.

In [7]:
import pandas as pd

x = [56, 52, 61, 63, 48, 68, 49, 59, 61, 62, 60, 55]

df = pd.DataFrame(x)
df.mean()

0    57.833333
dtype: float64

### Exemplo

Suponha que a média aritmética de um conjunto formado por 10 elementos seja igual a 8.
Se for acrescentado a esse conjunto o número 41, qual será a nova média?

Seja $x = (x_1, x_2, \ldots, x_10)$ os elementos desse conjunto.

$$
\overline{x} = \frac{\sum_{i=1}^{10} x_i }{10} = 8
$$

Temos que 
$$
\sum_{i=1}^{10} x_i = 80
$$
Se for acrescentado o número 41 ao conjunto, a soma dos elementos passará a ser
$ \sum_{i=1}^{10} x_i + 40 = 80 + 41$ e a média aritmética

$
\begin{align}
\overline{x} & = \frac{\sum_{i=1}^{10} x_i + 40}{11} \\
& = \frac{80 + 41}{11} \\
& = 11
\end{align}
$

### Proposição

Sejam $x_i$ para $i=1, 2, \ldots, n$ os valores associados a uma variável $x$, e $\overline{x}$ a média aritmética desses valores.
Se adicionarmos a cara elemento de $x$ uma constante $c$, a média aritmética aumentará em $c$ unidades.

### Prova da proposição
Considere que os novos valores assumidos por essa variável sejam:
$$
x = (x_1 + c, x_2 +c, \ldots, x_n + c)
$$
A nova média séra dada por
$$
\begin{align}
\overline{x}' & = \frac{\sum_{i=1}^{n} (x_i + c)}{n} \\
& = \frac{(x_1 + c) + (x_2 + c) + \ldots + (x_n + c) }{n} \\
& = \frac{\sum_{i=1}^{n} x_i}{n} + \frac{n \times c}{n} \\
& = \overline{x} + c
\end{align}
$$

### Proposição

Sejam $x_i$ para $i=1, 2, \ldots, n$ os valores associados a uma variável $x$, e $\overline{x}$ a média aritmética desses valores.
Se multiplicarmos cada elemento de $x$ por uma constante $c$, a média aritmética será multiplicadas por $c$ unidades.

### Prova da proposição
Considere que os novos valores assumidos por essa variável sejam:
$$
x = (x_1 \times c, x_2 \times c, \ldots, x_n \times c)
$$
A nova média séra dada por
$$
\begin{align}
\overline{x}' & = \frac{\sum_{i=1}^{n} (x_i \times c)}{n} \\
& = \frac{(x_1 \times c + x_2 \times c + \ldots + x_n \times c ) }{n} \\
& = c \times \frac{\sum_{i=1}^{n} x_i}{n} \\
& = c \times \overline{x}
\end{align}
$$

## Média aritmética ponderada

Seja $x = (x_1, x_2, \ldots, x_k)$ uma variável quantitativa com frequência absoluta $(n_1, n_2, \ldots, n_k)$.
A média aritmética ponderada ($\overline{x}$) é indicada como a divisão da soma de todos si produtos $x_i \times n_i$ para $i=1,2, \ldots, k$ pela soma das $k$ frequências absoluta, isto é
$$\overline{x} = \frac{\sum_{i=1}^{k} x_i \times n_i}{\sum_{i=1}^{k} n_i}
$$

A frequência relativa, $f_i$, é definida por $\frac{n_i}{\sum_{i=1}^{k} n_i}$.

É possível expressar a média aritmética por 
$$
\overline{x} = \sum_{i=1}^{k}  x_i \times f_i
$$

### Exemplo

Um feirante tem 50 kg de maçã para vender em um manhã. 
A seguir uma tabela com os período da vendar, preço do quilo e quantidade vendida por período.

In [11]:
import pandas as pd

# data frame
data = {
  "período": ["6h as 10h","10h as 11h", "11h as 12h"],
  "preço do kilo": [2.50, 2.00, 1.40],
  "kilos vendidos": [32, 13, 5]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

df

      período  preço do kilo  kilos vendidos
0   6h as 10h            2.5              32
1  10h as 11h            2.0              13
2  11h as 12h            1.4               5

Temos que naquela manhã o quilo da maça foi endido em média por
$
\begin{align}
\overline{x} & = \frac{32 \times 2.50 + 13 \times 2.00 + 5 \times 1.40}{32 + 13 + 5} \\
& = \frac{113}{50} \\
& \approx 2.26  
\end{align}
$

Dizemos que se trata de uma média aritmética ponderada dos preços, em que o fator de ponderação corresponde à quantidade de maçãs vendidas em cada período.

In [20]:
weighted_average = sum(df['kilos vendidos'] * df['preço do kilo']) / sum(df['kilos vendidos'])
weighted_average

2.26

### Exemplo
A fim de arrecadar recursos para uma festa de formatura, cada formando recebeu uma rifa com 20 números para vendê-los. 
Encerrado o prazo combinado, foi feito o levantamento de quantos números foram vendidos onde 10\% dos formandos venderam 10 números, 30$% venderam 15 números e o restante venderam 20 números.

A variável $x$ é a quantida de números vendidos, assim $x = (10, 15, 20)$.
A frequência relativa $f$ é definida por $f = (0.10, 0.30, 0.60)$.

A média aritmética com relação ao total de números vendidos por cada aluno é
$
\begin{align}
\overline{x} & = \sum_{i=1}^{3} x_i \times f_i \\
& = 10 \times 0.10 + 15 \times 0.30 + 20 \times 0.60 \\
& = 17.5 
\end{align}
$

Emmédia os formandos verderam 17.5 números da rifa.

censo_br_2002_densidade_demo
# lendo os dados
df_parque = pd.read_csv("../data/descritiva/perfil_freq_parque.csv",sep=';')

In [8]:
import pandas as pd
df = pd.read_csv("../data/censo_br_2002_densidade_demo.csv",sep=';')
df

    id               Estado  Densidade demográfica
0    1                 Acre                    3.7
1    2              Alagoas                  101.3
2    3                Amapá                    3.3
3    4             Amazonas                    1.8
4    5                Bahia                   23.2
5    6                Ceará                   50.9
6    7     Distrito Federal                  352.2
7    8       Espírito Santo                   67.2
8    9                Goiás                   14.7
9   10             Maranhão                   17.0
10  11          Mato Grosso                    2.8
11  12   Mato Grosso do Sul                    5.8
12  13         Minas Gerais                   30.5
13  14                 Pará                    5.0
14  15              Paraíba                   61.1
15  16               Paraná                   48.0
16  17           Pernambuco                   80.3
17  18                Piauí                   11.3
18  19       Rio de Janeiro                  328.0
19  20  Rio Grande do Norte                   52.2
20  21    Rio Grande do Sul                   36.1
21  22             Rondônia                    5.8
22  23              Roraima                    1.5
23  24       Santa Catarina                   56.1
24  25            São Paulo                  149.0
25  26              Sergipe                   81.1
26  27            Tocantins                    4.2

In [9]:
df.sort_values('Densidade demográfica', ascending=True, inplace=True)
df

    id               Estado  Densidade demográfica
22  23              Roraima                    1.5
3    4             Amazonas                    1.8
10  11          Mato Grosso                    2.8
2    3                Amapá                    3.3
0    1                 Acre                    3.7
26  27            Tocantins                    4.2
13  14                 Pará                    5.0
11  12   Mato Grosso do Sul                    5.8
21  22             Rondônia                    5.8
17  18                Piauí                   11.3
8    9                Goiás                   14.7
9   10             Maranhão                   17.0
4    5                Bahia                   23.2
12  13         Minas Gerais                   30.5
20  21    Rio Grande do Sul                   36.1
15  16               Paraná                   48.0
5    6                Ceará                   50.9
19  20  Rio Grande do Norte                   52.2
23  24       Santa Catarina                   56.1
14  15              Paraíba                   61.1
7    8       Espírito Santo                   67.2
16  17           Pernambuco                   80.3
25  26              Sergipe                   81.1
1    2              Alagoas                  101.3
24  25            São Paulo                  149.0
18  19       Rio de Janeiro                  328.0
6    7     Distrito Federal                  352.2